name: Observability Libs CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  static-analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run static analysis (lib)
        run: tox -vve static-lib
      - name: Run static analysis (charm)
        run: tox -vve static-charm
      - name: Run static analysis (unit tests)
        run: tox -vve static-unit
      - name: Run static analysis (integration tests)
        run: tox -vve static-integration
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run linters
        run: tox -vve lint
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: python -m pip install tox
      - name: Run tests
        run: tox -vve unit
  integration-test:
    name: Integration tests (microk8s)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          juju-channel: latest/stable
          provider: microk8s
          bootstrap-options: "--agent-version 2.9.29"
      - name: Run integration tests
        run: tox -vve integration
