name: Pull Request

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  discover:
    uses: ./.github/workflows/_discover-changed-packages.yaml

  check:
    name: Check (${{ matrix.package }})
    needs: discover
    if: ${{ needs.discover.outputs.packages != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.discover.outputs.packages) }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.package }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          sudo snap install astral-uv --classic
          sudo snap install just --classic
      - name: Check
        run: just check
